### PR TITLE
Segmented symbols

### PR DESCRIPTION
**Pull request by Knochi**
I created a module to generate 16-segment display style patterns. There is a wheel that contains all segments isolated and some common combinations.
Letters and numbers must be combined by pressing multiple segments without feeding the tape

### CODE REVIEW

**Review by andreisperid — APPROVED** [review]

**Comment by andreisperid** [comment]
That's interesting and that idea might lead to a braile press 💡

**Comment by Knochi** [comment]
Haha yes Braille is the next I‘m looking at.
And I have an idea of a dot Matrix Implantation, but that would require quite high precision of the feeder mechanism.
What do you think is the precision and repeatability?

**Comment by andreisperid** [comment]
I guess you might be wanting to use a 3 individual press vertical inline + feed for both advancing the horizontal lines and spaces, right? Instead of the daisy wheel?

Right now the biggest imprecisions on feeding are because of:
1 - this specific stepper motor isn't strong enough, eventually missing steps
2 - the tape occasionally slips, because the extruder gear doesn't fit tight on the stepper motor axis (even with the screw, it gets a bit eccentric

For a totally new design, I guess a NEMA for the extruder would be better. I was thinking about doing a different machine just for braille.

**Comment by Knochi** [comment]
For Braille I think we can go with the current design. 

I was thinking of printing a pixel matrix of 5x8 dots by having just columns of dots, single ones and common combinations.

**Pull request merged**
